name: Build and Publish Favourite Albums (Pages)

on:
  schedule:
    - cron: "5 6 * * *"   # daily 06:05 UTC
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore & build
        run: dotnet build -c Release

      - name: Run worker to generate HTML
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          STAR_PLAYLISTS: '5:3Rs7e9KMwxCJroMpvMDpL8,4:3DGYY0Hj4RzydffF170y3Z,3:5noq8iSiMjSLH2e9t11NOv,2:1ABB6n1AFfTUEJTfCaopAY,1:532lvkCpc2oYKvmD4UmN0f'
          FILLER_PLAYLIST_ID: 4GDdPGifkYK7WWk7HmL67v
          EXCLUDED_PLAYLIST_ID: 2X8xwVpmCg0erBpNK9VgP3
          EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
          EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
          EBAY_MARKETPLACE: EBAY_GB
          EBAY_DELIVERY_CC: GB
          EBAY_MAX_PRICE_GBP: '25'
          EBAY_QUERY_CONCURRENCY: '3'
          EBAY_PAGES_PER_QUERY: '2'
          EBAY_LIMIT_PER_PAGE: '50'
          EBAY_MAX_RESULTS: '400'
      
          OUTPUT_DIR:              out
          DETAIL_FETCH_CONCURRENCY: 4
        run: dotnet run --project FavouriteAlbums.Worker/FavouriteAlbums.Worker.csproj -c Release

      - name: Verify artifact exists
        run: test -f out/index.html

      # Make Pages remember the custom domain
      - name: Add CNAME file
        run: echo "albums.mattdurrant.com" > out/CNAME

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
